packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@better-auth/cli": 1.4.6
  "@better-auth/expo": 1.4.6
  "@eslint/js": ^9.39.1
  "@tailwindcss/postcss": ^4.1.18
  "@tailwindcss/vite": ^4.1.18
  "@tanstack/react-form": ^1.27.3
  "@tanstack/react-query": ^5.90.12
  "@trpc/client": ^11.7.2
  "@trpc/server": ^11.7.2
  "@trpc/tanstack-react-query": ^11.7.2
  "@types/node": ^24.10.3
  "@vitejs/plugin-react": 5.1.2
  better-auth: 1.4.6
  eslint: ^9.39.1
  kysely: 0.28.8
  prettier: ^3.7.4
  tailwindcss: ^4.1.18
  typescript: ^5.9.3
  zod: ^4.1.13
  vite: 7.2.7

catalogs:
  react19:
    "@types/react": ~19.1.0
    "@types/react-dom": ~19.1.0
    react: 19.1.4
    react-dom: 19.1.4

linkWorkspacePackages: true

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild

overrides:
  "@types/minimatch": 6.0.0
  vite: 7.2.7
  lightningcss: 1.30.1

publicHoistPattern:
  - "@ianvs/prettier-plugin-sort-imports"
  - prettier-plugin-tailwindcss
  - pg
