packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@better-auth/cli": 1.4.1
  "@better-auth/expo": 1.4.1
  "@eslint/js": ^9.39.1
  "@tailwindcss/postcss": ^4.1.17
  "@tailwindcss/vite": ^4.1.17
  "@tanstack/react-form": ^1.25.0
  "@tanstack/react-query": ^5.90.10
  "@trpc/client": ^11.7.2
  "@trpc/server": ^11.7.2
  "@trpc/tanstack-react-query": ^11.7.2
  "@types/node": ^24.10.1
  "@vitejs/plugin-react": 5.1.1
  better-auth: 1.4.1
  eslint: ^9.39.1
  kysely: 0.28.8
  prettier: ^3.6.2
  tailwindcss: ^4.1.17
  typescript: ^5.9.3
  zod: ^4.1.12
  vite: 7.2.4

catalogs:
  react19:
    "@types/react": ^19.1.12
    "@types/react-dom": ^19.1.9
    react: 19.1.1
    react-dom: 19.1.1

linkWorkspacePackages: true

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild

overrides:
  "@types/minimatch": 6.0.0
  vite: 7.2.4
  lightningcss: 1.30.1

publicHoistPattern:
  - "@ianvs/prettier-plugin-sort-imports"
  - prettier-plugin-tailwindcss
  - pg
