packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@better-auth/cli": 1.4.10
  "@better-auth/expo": 1.4.10
  "@eslint/js": ^9.39.2
  "@tailwindcss/postcss": ^4.1.18
  "@tailwindcss/vite": ^4.1.18
  "@tanstack/react-form": ^1.27.7
  "@tanstack/react-query": ^5.90.16
  "@trpc/client": ^11.8.1
  "@trpc/server": ^11.8.1
  "@trpc/tanstack-react-query": ^11.8.1
  "@types/node": ^24.10.4
  "@vitejs/plugin-react": 5.1.2
  better-auth: 1.4.10
  eslint: ^9.39.2
  kysely: 0.28.9
  prettier: ^3.7.4
  tailwindcss: ^4.1.18
  typescript: ^5.9.3
  zod: ^4.3.2
  vite: 7.3.0

catalogs:
  react19:
    "@types/react": ~19.1.0
    "@types/react-dom": ~19.1.0
    react: 19.1.4
    react-dom: 19.1.4

linkWorkspacePackages: true

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild

overrides:
  "@types/minimatch": 6.0.0
  vite: 7.3.0
  lightningcss: 1.30.1

publicHoistPattern:
  - "@ianvs/prettier-plugin-sort-imports"
  - prettier-plugin-tailwindcss
  - pg
