/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as PlateRouteImport } from './routes/plate'
import { Route as OrganizationsRouteImport } from './routes/organizations'
import { Route as LandRouteImport } from './routes/land'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthLayoutRouteImport } from './routes/auth/layout'
import { Route as AuthenticatedLayoutRouteImport } from './routes/_authenticated/layout'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedProductsIndexRouteImport } from './routes/_authenticated/products/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedGasIndexRouteImport } from './routes/_authenticated/gas/index'
import { Route as AuthenticatedClientsIndexRouteImport } from './routes/_authenticated/clients/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsLayoutRouteImport } from './routes/_authenticated/settings/layout'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedProductsNewRouteImport } from './routes/_authenticated/products/new'
import { Route as AuthenticatedProductsLayoutRouteImport } from './routes/_authenticated/products/layout'
import { Route as AuthenticatedProductsProductIdRouteImport } from './routes/_authenticated/products/$productId'
import { Route as AuthenticatedGasReportsRouteImport } from './routes/_authenticated/gas/reports'
import { Route as AuthenticatedGasLayoutRouteImport } from './routes/_authenticated/gas/layout'
import { Route as AuthenticatedGasEntryRouteImport } from './routes/_authenticated/gas/entry'
import { Route as AuthenticatedGasAdminRouteImport } from './routes/_authenticated/gas/admin'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedClientsNewRouteImport } from './routes/_authenticated/clients/new'
import { Route as AuthenticatedClientsLayoutRouteImport } from './routes/_authenticated/clients/layout'
import { Route as AuthenticatedClientsClientIdRouteImport } from './routes/_authenticated/clients/$clientId'
import { Route as AuthenticatedAdminOrganizationsIndexRouteImport } from './routes/_authenticated/admin/organizations/index'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const PlateRoute = PlateRouteImport.update({
  id: '/plate',
  path: '/plate',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsRoute = OrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const LandRoute = LandRouteImport.update({
  id: '/land',
  path: '/land',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/_authenticated/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/auth/layout',
  path: '/auth/layout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLayoutRoute = AuthenticatedLayoutRouteImport.update({
  id: '/_authenticated/layout',
  path: '/layout',
  getParentRoute: () => rootRouteImport,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/_authenticated/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/_authenticated/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/_authenticated/settings/',
    path: '/settings/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedProductsIndexRoute =
  AuthenticatedProductsIndexRouteImport.update({
    id: '/_authenticated/products/',
    path: '/products/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/_authenticated/help-center/',
    path: '/help-center/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedGasIndexRoute = AuthenticatedGasIndexRouteImport.update({
  id: '/_authenticated/gas/',
  path: '/gas/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedClientsIndexRoute =
  AuthenticatedClientsIndexRouteImport.update({
    id: '/_authenticated/clients/',
    path: '/clients/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/_authenticated/chats/',
  path: '/chats/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/_authenticated/apps/',
  path: '/apps/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/_authenticated/settings/notifications',
    path: '/settings/notifications',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSettingsLayoutRoute =
  AuthenticatedSettingsLayoutRouteImport.update({
    id: '/_authenticated/settings/layout',
    path: '/settings/layout',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/_authenticated/settings/display',
    path: '/settings/display',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/_authenticated/settings/appearance',
    path: '/settings/appearance',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/_authenticated/settings/account',
    path: '/settings/account',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedProductsNewRoute =
  AuthenticatedProductsNewRouteImport.update({
    id: '/_authenticated/products/new',
    path: '/products/new',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedProductsLayoutRoute =
  AuthenticatedProductsLayoutRouteImport.update({
    id: '/_authenticated/products/layout',
    path: '/products/layout',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedProductsProductIdRoute =
  AuthenticatedProductsProductIdRouteImport.update({
    id: '/_authenticated/products/$productId',
    path: '/products/$productId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedGasReportsRoute = AuthenticatedGasReportsRouteImport.update({
  id: '/_authenticated/gas/reports',
  path: '/gas/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedGasLayoutRoute = AuthenticatedGasLayoutRouteImport.update({
  id: '/_authenticated/gas/layout',
  path: '/gas/layout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedGasEntryRoute = AuthenticatedGasEntryRouteImport.update({
  id: '/_authenticated/gas/entry',
  path: '/gas/entry',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedGasAdminRoute = AuthenticatedGasAdminRouteImport.update({
  id: '/_authenticated/gas/admin',
  path: '/gas/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/_authenticated/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedClientsNewRoute = AuthenticatedClientsNewRouteImport.update({
  id: '/_authenticated/clients/new',
  path: '/clients/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedClientsLayoutRoute =
  AuthenticatedClientsLayoutRouteImport.update({
    id: '/_authenticated/clients/layout',
    path: '/clients/layout',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedClientsClientIdRoute =
  AuthenticatedClientsClientIdRouteImport.update({
    id: '/_authenticated/clients/$clientId',
    path: '/clients/$clientId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminOrganizationsIndexRoute =
  AuthenticatedAdminOrganizationsIndexRouteImport.update({
    id: '/_authenticated/admin/organizations/',
    path: '/admin/organizations/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/land': typeof LandRoute
  '/organizations': typeof OrganizationsRoute
  '/plate': typeof PlateRoute
  '/test': typeof TestRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/layout': typeof AuthenticatedLayoutRoute
  '/auth/layout': typeof AuthLayoutRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/': typeof AuthenticatedIndexRoute
  '/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/clients/layout': typeof AuthenticatedClientsLayoutRoute
  '/clients/new': typeof AuthenticatedClientsNewRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/gas/admin': typeof AuthenticatedGasAdminRoute
  '/gas/entry': typeof AuthenticatedGasEntryRoute
  '/gas/layout': typeof AuthenticatedGasLayoutRoute
  '/gas/reports': typeof AuthenticatedGasReportsRoute
  '/products/$productId': typeof AuthenticatedProductsProductIdRoute
  '/products/layout': typeof AuthenticatedProductsLayoutRoute
  '/products/new': typeof AuthenticatedProductsNewRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/layout': typeof AuthenticatedSettingsLayoutRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/apps/': typeof AuthenticatedAppsIndexRoute
  '/chats/': typeof AuthenticatedChatsIndexRoute
  '/clients/': typeof AuthenticatedClientsIndexRoute
  '/gas/': typeof AuthenticatedGasIndexRoute
  '/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/products/': typeof AuthenticatedProductsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/tasks/': typeof AuthenticatedTasksIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/admin/organizations/': typeof AuthenticatedAdminOrganizationsIndexRoute
}
export interface FileRoutesByTo {
  '/land': typeof LandRoute
  '/organizations': typeof OrganizationsRoute
  '/plate': typeof PlateRoute
  '/test': typeof TestRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/layout': typeof AuthenticatedLayoutRoute
  '/auth/layout': typeof AuthLayoutRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/': typeof AuthenticatedIndexRoute
  '/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/clients/layout': typeof AuthenticatedClientsLayoutRoute
  '/clients/new': typeof AuthenticatedClientsNewRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/gas/admin': typeof AuthenticatedGasAdminRoute
  '/gas/entry': typeof AuthenticatedGasEntryRoute
  '/gas/layout': typeof AuthenticatedGasLayoutRoute
  '/gas/reports': typeof AuthenticatedGasReportsRoute
  '/products/$productId': typeof AuthenticatedProductsProductIdRoute
  '/products/layout': typeof AuthenticatedProductsLayoutRoute
  '/products/new': typeof AuthenticatedProductsNewRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/layout': typeof AuthenticatedSettingsLayoutRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
  '/gas': typeof AuthenticatedGasIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/products': typeof AuthenticatedProductsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/admin/organizations': typeof AuthenticatedAdminOrganizationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/land': typeof LandRoute
  '/organizations': typeof OrganizationsRoute
  '/plate': typeof PlateRoute
  '/test': typeof TestRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/layout': typeof AuthenticatedLayoutRoute
  '/auth/layout': typeof AuthLayoutRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/_authenticated/clients/layout': typeof AuthenticatedClientsLayoutRoute
  '/_authenticated/clients/new': typeof AuthenticatedClientsNewRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/gas/admin': typeof AuthenticatedGasAdminRoute
  '/_authenticated/gas/entry': typeof AuthenticatedGasEntryRoute
  '/_authenticated/gas/layout': typeof AuthenticatedGasLayoutRoute
  '/_authenticated/gas/reports': typeof AuthenticatedGasReportsRoute
  '/_authenticated/products/$productId': typeof AuthenticatedProductsProductIdRoute
  '/_authenticated/products/layout': typeof AuthenticatedProductsLayoutRoute
  '/_authenticated/products/new': typeof AuthenticatedProductsNewRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/layout': typeof AuthenticatedSettingsLayoutRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/clients/': typeof AuthenticatedClientsIndexRoute
  '/_authenticated/gas/': typeof AuthenticatedGasIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/products/': typeof AuthenticatedProductsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/admin/organizations/': typeof AuthenticatedAdminOrganizationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/land'
    | '/organizations'
    | '/plate'
    | '/test'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/layout'
    | '/auth/layout'
    | '/auth/login'
    | '/auth/register'
    | '/'
    | '/clients/$clientId'
    | '/clients/layout'
    | '/clients/new'
    | '/errors/$error'
    | '/gas/admin'
    | '/gas/entry'
    | '/gas/layout'
    | '/gas/reports'
    | '/products/$productId'
    | '/products/layout'
    | '/products/new'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/layout'
    | '/settings/notifications'
    | '/apps/'
    | '/chats/'
    | '/clients/'
    | '/gas/'
    | '/help-center/'
    | '/products/'
    | '/settings/'
    | '/tasks/'
    | '/users/'
    | '/admin/organizations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/land'
    | '/organizations'
    | '/plate'
    | '/test'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/layout'
    | '/auth/layout'
    | '/auth/login'
    | '/auth/register'
    | '/'
    | '/clients/$clientId'
    | '/clients/layout'
    | '/clients/new'
    | '/errors/$error'
    | '/gas/admin'
    | '/gas/entry'
    | '/gas/layout'
    | '/gas/reports'
    | '/products/$productId'
    | '/products/layout'
    | '/products/new'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/layout'
    | '/settings/notifications'
    | '/apps'
    | '/chats'
    | '/clients'
    | '/gas'
    | '/help-center'
    | '/products'
    | '/settings'
    | '/tasks'
    | '/users'
    | '/admin/organizations'
  id:
    | '__root__'
    | '/land'
    | '/organizations'
    | '/plate'
    | '/test'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/layout'
    | '/auth/layout'
    | '/auth/login'
    | '/auth/register'
    | '/_authenticated/'
    | '/_authenticated/clients/$clientId'
    | '/_authenticated/clients/layout'
    | '/_authenticated/clients/new'
    | '/_authenticated/errors/$error'
    | '/_authenticated/gas/admin'
    | '/_authenticated/gas/entry'
    | '/_authenticated/gas/layout'
    | '/_authenticated/gas/reports'
    | '/_authenticated/products/$productId'
    | '/_authenticated/products/layout'
    | '/_authenticated/products/new'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/layout'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/apps/'
    | '/_authenticated/chats/'
    | '/_authenticated/clients/'
    | '/_authenticated/gas/'
    | '/_authenticated/help-center/'
    | '/_authenticated/products/'
    | '/_authenticated/settings/'
    | '/_authenticated/tasks/'
    | '/_authenticated/users/'
    | '/_authenticated/admin/organizations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LandRoute: typeof LandRoute
  OrganizationsRoute: typeof OrganizationsRoute
  PlateRoute: typeof PlateRoute
  TestRoute: typeof TestRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
  AuthenticatedLayoutRoute: typeof AuthenticatedLayoutRoute
  AuthLayoutRoute: typeof AuthLayoutRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedClientsClientIdRoute: typeof AuthenticatedClientsClientIdRoute
  AuthenticatedClientsLayoutRoute: typeof AuthenticatedClientsLayoutRoute
  AuthenticatedClientsNewRoute: typeof AuthenticatedClientsNewRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedGasAdminRoute: typeof AuthenticatedGasAdminRoute
  AuthenticatedGasEntryRoute: typeof AuthenticatedGasEntryRoute
  AuthenticatedGasLayoutRoute: typeof AuthenticatedGasLayoutRoute
  AuthenticatedGasReportsRoute: typeof AuthenticatedGasReportsRoute
  AuthenticatedProductsProductIdRoute: typeof AuthenticatedProductsProductIdRoute
  AuthenticatedProductsLayoutRoute: typeof AuthenticatedProductsLayoutRoute
  AuthenticatedProductsNewRoute: typeof AuthenticatedProductsNewRoute
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsLayoutRoute: typeof AuthenticatedSettingsLayoutRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedClientsIndexRoute: typeof AuthenticatedClientsIndexRoute
  AuthenticatedGasIndexRoute: typeof AuthenticatedGasIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedProductsIndexRoute: typeof AuthenticatedProductsIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedAdminOrganizationsIndexRoute: typeof AuthenticatedAdminOrganizationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plate': {
      id: '/plate'
      path: '/plate'
      fullPath: '/plate'
      preLoaderRoute: typeof PlateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations': {
      id: '/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof OrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/land': {
      id: '/land'
      path: '/land'
      fullPath: '/land'
      preLoaderRoute: typeof LandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/layout': {
      id: '/auth/layout'
      path: '/auth/layout'
      fullPath: '/auth/layout'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/layout': {
      id: '/_authenticated/layout'
      path: '/layout'
      fullPath: '/layout'
      preLoaderRoute: typeof AuthenticatedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/products/': {
      id: '/_authenticated/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthenticatedProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center/'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/gas/': {
      id: '/_authenticated/gas/'
      path: '/gas'
      fullPath: '/gas/'
      preLoaderRoute: typeof AuthenticatedGasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/clients/': {
      id: '/_authenticated/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthenticatedClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats/'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/layout': {
      id: '/_authenticated/settings/layout'
      path: '/settings/layout'
      fullPath: '/settings/layout'
      preLoaderRoute: typeof AuthenticatedSettingsLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/settings/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/settings/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/settings/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/products/new': {
      id: '/_authenticated/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof AuthenticatedProductsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/products/layout': {
      id: '/_authenticated/products/layout'
      path: '/products/layout'
      fullPath: '/products/layout'
      preLoaderRoute: typeof AuthenticatedProductsLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/products/$productId': {
      id: '/_authenticated/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof AuthenticatedProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/gas/reports': {
      id: '/_authenticated/gas/reports'
      path: '/gas/reports'
      fullPath: '/gas/reports'
      preLoaderRoute: typeof AuthenticatedGasReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/gas/layout': {
      id: '/_authenticated/gas/layout'
      path: '/gas/layout'
      fullPath: '/gas/layout'
      preLoaderRoute: typeof AuthenticatedGasLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/gas/entry': {
      id: '/_authenticated/gas/entry'
      path: '/gas/entry'
      fullPath: '/gas/entry'
      preLoaderRoute: typeof AuthenticatedGasEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/gas/admin': {
      id: '/_authenticated/gas/admin'
      path: '/gas/admin'
      fullPath: '/gas/admin'
      preLoaderRoute: typeof AuthenticatedGasAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/clients/new': {
      id: '/_authenticated/clients/new'
      path: '/clients/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof AuthenticatedClientsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/clients/layout': {
      id: '/_authenticated/clients/layout'
      path: '/clients/layout'
      fullPath: '/clients/layout'
      preLoaderRoute: typeof AuthenticatedClientsLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/clients/$clientId': {
      id: '/_authenticated/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof AuthenticatedClientsClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/organizations/': {
      id: '/_authenticated/admin/organizations/'
      path: '/admin/organizations'
      fullPath: '/admin/organizations/'
      preLoaderRoute: typeof AuthenticatedAdminOrganizationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  LandRoute: LandRoute,
  OrganizationsRoute: OrganizationsRoute,
  PlateRoute: PlateRoute,
  TestRoute: TestRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
  AuthenticatedLayoutRoute: AuthenticatedLayoutRoute,
  AuthLayoutRoute: AuthLayoutRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedClientsClientIdRoute: AuthenticatedClientsClientIdRoute,
  AuthenticatedClientsLayoutRoute: AuthenticatedClientsLayoutRoute,
  AuthenticatedClientsNewRoute: AuthenticatedClientsNewRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedGasAdminRoute: AuthenticatedGasAdminRoute,
  AuthenticatedGasEntryRoute: AuthenticatedGasEntryRoute,
  AuthenticatedGasLayoutRoute: AuthenticatedGasLayoutRoute,
  AuthenticatedGasReportsRoute: AuthenticatedGasReportsRoute,
  AuthenticatedProductsProductIdRoute: AuthenticatedProductsProductIdRoute,
  AuthenticatedProductsLayoutRoute: AuthenticatedProductsLayoutRoute,
  AuthenticatedProductsNewRoute: AuthenticatedProductsNewRoute,
  AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
  AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
  AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
  AuthenticatedSettingsLayoutRoute: AuthenticatedSettingsLayoutRoute,
  AuthenticatedSettingsNotificationsRoute:
    AuthenticatedSettingsNotificationsRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedClientsIndexRoute: AuthenticatedClientsIndexRoute,
  AuthenticatedGasIndexRoute: AuthenticatedGasIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedProductsIndexRoute: AuthenticatedProductsIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedAdminOrganizationsIndexRoute:
    AuthenticatedAdminOrganizationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
