//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { schema as $schema, type SchemaType as $Schema } from "./schema";
import { type ModelResult as $ModelResult, type TypeDefResult as $TypeDefResult } from "@zenstackhq/orm";
export type User = $ModelResult<$Schema, "User">;
export type Session = $ModelResult<$Schema, "Session">;
export type Account = $ModelResult<$Schema, "Account">;
export type Verification = $ModelResult<$Schema, "Verification">;
export type Organization = $ModelResult<$Schema, "Organization">;
export type Member = $ModelResult<$Schema, "Member">;
export type Invitation = $ModelResult<$Schema, "Invitation">;
export type Todo = $ModelResult<$Schema, "Todo">;
export type Test = $ModelResult<$Schema, "Test">;
export type Product = $ModelResult<$Schema, "Product">;
export type Client = $ModelResult<$Schema, "Client">;
export type OnboardingProcess = $ModelResult<$Schema, "OnboardingProcess">;
export type OnboardingDocument = $ModelResult<$Schema, "OnboardingDocument">;
export type OnboardingChat = $ModelResult<$Schema, "OnboardingChat">;
export type KnowledgeChat = $ModelResult<$Schema, "KnowledgeChat">;
export type GroupChatMessage = $ModelResult<$Schema, "GroupChatMessage">;
export type OnboardingChecklistStep = $ModelResult<$Schema, "OnboardingChecklistStep">;
export type OnboardingChecklistProgress = $ModelResult<$Schema, "OnboardingChecklistProgress">;
export type CalendarEvent = $ModelResult<$Schema, "CalendarEvent">;
export type KanbanBoard = $ModelResult<$Schema, "KanbanBoard">;
export type KanbanColumn = $ModelResult<$Schema, "KanbanColumn">;
export type KanbanCard = $ModelResult<$Schema, "KanbanCard">;
export type SalesOrder = $ModelResult<$Schema, "SalesOrder">;
export type OrderItem = $ModelResult<$Schema, "OrderItem">;
export type UserScore = $ModelResult<$Schema, "UserScore">;
export type Achievement = $ModelResult<$Schema, "Achievement">;
export type UserAchievement = $ModelResult<$Schema, "UserAchievement">;
export type UserActionCount = $ModelResult<$Schema, "UserActionCount">;
export type TutorialSector = $ModelResult<$Schema, "TutorialSector">;
export type TutorialSection = $ModelResult<$Schema, "TutorialSection">;
export type TutorialStep = $ModelResult<$Schema, "TutorialStep">;
export type TutorialStepProgress = $ModelResult<$Schema, "TutorialStepProgress">;
export type GasUnit = $ModelResult<$Schema, "GasUnit">;
export type GasEquipment = $ModelResult<$Schema, "GasEquipment">;
export type GasEquipmentConstant = $ModelResult<$Schema, "GasEquipmentConstant">;
export type GasDailyEntry = $ModelResult<$Schema, "GasDailyEntry">;
export type GasLineStatus = $ModelResult<$Schema, "GasLineStatus">;
export type GasDailyPlan = $ModelResult<$Schema, "GasDailyPlan">;
export type GasRealConsumption = $ModelResult<$Schema, "GasRealConsumption">;
export type GasContract = $ModelResult<$Schema, "GasContract">;
export type GasContractAuditLog = $ModelResult<$Schema, "GasContractAuditLog">;
export type GasUnitOperator = $ModelResult<$Schema, "GasUnitOperator">;
export type UserNotificationPreferences = $ModelResult<$Schema, "UserNotificationPreferences">;
/**
 * Shape of the `auth()` function
 */
export type Auth = $TypeDefResult<$Schema, "Auth">;
export const UserRole = $schema.enums.UserRole.values;
export type UserRole = (typeof UserRole)[keyof typeof UserRole];
export const MemberRole = $schema.enums.MemberRole.values;
export type MemberRole = (typeof MemberRole)[keyof typeof MemberRole];
export const GasUserProfile = $schema.enums.GasUserProfile.values;
export type GasUserProfile = (typeof GasUserProfile)[keyof typeof GasUserProfile];
export const ClientStatus = $schema.enums.ClientStatus.values;
export type ClientStatus = (typeof ClientStatus)[keyof typeof ClientStatus];
export const EmployeeType = $schema.enums.EmployeeType.values;
export type EmployeeType = (typeof EmployeeType)[keyof typeof EmployeeType];
export const ChatRole = $schema.enums.ChatRole.values;
export type ChatRole = (typeof ChatRole)[keyof typeof ChatRole];
export const OrderStatus = $schema.enums.OrderStatus.values;
export type OrderStatus = (typeof OrderStatus)[keyof typeof OrderStatus];
export const MilestoneType = $schema.enums.MilestoneType.values;
export type MilestoneType = (typeof MilestoneType)[keyof typeof MilestoneType];
export const EquipmentType = $schema.enums.EquipmentType.values;
export type EquipmentType = (typeof EquipmentType)[keyof typeof EquipmentType];
export const ConsumptionUnit = $schema.enums.ConsumptionUnit.values;
export type ConsumptionUnit = (typeof ConsumptionUnit)[keyof typeof ConsumptionUnit];
export const LineStatusValue = $schema.enums.LineStatusValue.values;
export type LineStatusValue = (typeof LineStatusValue)[keyof typeof LineStatusValue];
export const ConsumptionSource = $schema.enums.ConsumptionSource.values;
export type ConsumptionSource = (typeof ConsumptionSource)[keyof typeof ConsumptionSource];
