//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import type {
	ModelResult as $ModelResult,
	TypeDefResult as $TypeDefResult,
} from "@zenstackhq/orm";
import { type SchemaType as $Schema, schema as $schema } from "./schema";
export type User = $ModelResult<$Schema, "User">;
export type Session = $ModelResult<$Schema, "Session">;
export type Account = $ModelResult<$Schema, "Account">;
export type Verification = $ModelResult<$Schema, "Verification">;
export type Organization = $ModelResult<$Schema, "Organization">;
export type Member = $ModelResult<$Schema, "Member">;
export type Invitation = $ModelResult<$Schema, "Invitation">;
export type Todo = $ModelResult<$Schema, "Todo">;
export type Test = $ModelResult<$Schema, "Test">;
export type Product = $ModelResult<$Schema, "Product">;
export type Client = $ModelResult<$Schema, "Client">;
/**
 * Shape of the `auth()` function
 */
export type Auth = $TypeDefResult<$Schema, "Auth">;
export const UserRole = $schema.enums.UserRole.values;
export type UserRole = (typeof UserRole)[keyof typeof UserRole];
export const MemberRole = $schema.enums.MemberRole.values;
export type MemberRole = (typeof MemberRole)[keyof typeof MemberRole];
export const ClientStatus = $schema.enums.ClientStatus.values;
export type ClientStatus = (typeof ClientStatus)[keyof typeof ClientStatus];
